#!/bin/bash

clear
if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "คำสั่งนี้ยังไม่รองรับระบบปฏิบัติการอื่นนอกจาก Debian, Ubuntu และ CentOS"
	exit
fi
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "--------- MENU SCRIPT ---------"
	echo ""
	echo -e "|${color1} 1${color3}| เพิ่มชื่อผู้ใช้"
	echo -e "|${color1} 2${color3}| ลบชื่อผู้ใช้"
	echo -e "|${color1} 3${color3}| รายชื่อผู้ใช้ทั้งหมด"
	echo -e "|${color1} 4${color3}| ตั้งค่ารีบูทเซิฟเวอร์อัตโนมัติ"
	echo -e "|${color1} 5${color3}| รายชื่อผู้ใช้ที่กำลังออนไลน์"
	echo -e "|${color1} 6${color3}| แบนชื่อผู้ใช้"
	echo -e "|${color1} 7${color3}| ปลดแบนชื่อผู้ใช้"
	echo -e "|${color1} 8${color3}| ตรวจสอบดาต้าที่ใช้ไปทั้งหมดในปัจจุบัน"
	echo -e "|${color1} 9${color3}| Speedtest Server"
	echo -e "|${color1}10${color3}| Restart Service"
	echo -e "|${color1}11${color3}| อัพเดตเมนู"
	echo -e "|${color1}12${color3}| ยกเลิก"
	echo -e ""
	
	read -p "กรุณาเลือกหัวข้อที่ต้องการใช้งาน (ตัวเลข)  : " x
if test $x -eq 1; then
	echo ""
	read -p "Username : " Login
	echo ""
	read -p "Password : " Passwd
	echo ""
	read -p "Expired (Day) : " TimeActive

	IP=`dig +short myip.opendns.com @resolver1.opendns.com`
	useradd -e `date -d "$TimeActive days" +"%Y-%m-%d"` -s /bin/false -M $Login
	exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
	echo -e "$Passwd\n$Passwd\n"|passwd $Login &> /dev/null

cd /etc/openvpn/
cat > /etc/openvpn/$Login.ovpn <<END
client
dev tun
proto tcp
remote $IP:1194@lvs.truehits.in.th.static.tlcdn4.com.naver.jp 1194
http-proxy $IP 8080
http-proxy-retry
connect-retry 1
connect-timeout 120
resolv-retry infinite
route-method exe
nobind
ping 5
ping-restart 30
persist-key
persist-tun
persist-remote-ip
mute-replay-warnings
verb 3
sndbuf 393216
rcvbuf 393216
push "sndbuf 393216"
push "rcvbuf 393216"
<auth-user-pass>
$Login
$Passwd
</auth-user-pass>
cipher none
comp-lzo
script-security 3
key-proxy-DNS 8.8.8.8
key-proxy-DNS 8.8.4.4

<ca>
-----BEGIN CERTIFICATE-----
MIID4DCCA0mgAwIBAgIJAM3S4jaLTQBoMA0GCSqGSIb3DQEBBQUAMIGnMQswCQYD
VQQGEwJJRDERMA8GA1UECBMIV2VzdEphdmExDjAMBgNVBAcTBUJvZ29yMRQwEgYD
VQQKEwtKdWFsU1NILmNvbTEUMBIGA1UECxMLSnVhbFNTSC5jb20xFDASBgNVBAMT
C0p1YWxTU0guY29tMRQwEgYDVQQpEwtKdWFsU1NILmNvbTEdMBsGCSqGSIb3DQEJ
ARYObWVAanVhbHNzaC5jb20wHhcNMTMxMTA4MTQwODA3WhcNMjMxMTA2MTQwODA3
WjCBpzELMAkGA1UEBhMCSUQxETAPBgNVBAgTCFdlc3RKYXZhMQ4wDAYDVQQHEwVC
b2dvcjEUMBIGA1UEChMLSnVhbFNTSC5jb20xFDASBgNVBAsTC0p1YWxTU0guY29t
MRQwEgYDVQQDEwtKdWFsU1NILmNvbTEUMBIGA1UEKRMLSnVhbFNTSC5jb20xHTAb
BgkqhkiG9w0BCQEWDm1lQGp1YWxzc2guY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDO0s4v72Y+V1z3XpkQD8hVjYyJk1PzpaNGpubtVXf7b/2vhvYBfE3X
46NvpgQejsAI4rW7XWMZrAjFzQBPE0zDAt1O0ukvGRFvHr16jLuC3cZCn3oQJ0+v
HD7Z16sUhKqLWRTGAf1LDvNR3eVmzzRfBF8L3h+ZGaQFW9gsw1tSSwIDAQABo4IB
EDCCAQwwHQYDVR0OBBYEFA5gsoPi0yORhvAA38zCXOQhX4wYMIHcBgNVHSMEgdQw
gdGAFA5gsoPi0yORhvAA38zCXOQhX4wYoYGtpIGqMIGnMQswCQYDVQQGEwJJRDER
MA8GA1UECBMIV2VzdEphdmExDjAMBgNVBAcTBUJvZ29yMRQwEgYDVQQKEwtKdWFs
U1NILmNvbTEUMBIGA1UECxMLSnVhbFNTSC5jb20xFDASBgNVBAMTC0p1YWxTU0gu
Y29tMRQwEgYDVQQpEwtKdWFsU1NILmNvbTEdMBsGCSqGSIb3DQEJARYObWVAanVh
bHNzaC5jb22CCQDN0uI2i00AaDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUA
A4GBAL3ScsXaFFuBqkS8bDqDUkx2hYM2iAYx9ZEuz8DOgtenQiNcyety4YzWSE5b
1/4JSlrO0hoFAZpz6tZtB9XM5efx5zSEIn+w4+2bWUk34Ro2zM3JxwDUp1tTcpbT
T0G3VTuVrzgSMZV1unfbCHk6XR4VT3MmmoTl+97cmmMZgWV0
-----END CERTIFICATE-----
</ca>
END

	cp $Login.ovpn /home/vps/public_html/
	cd
	echo -e ""
	echo -e "======== Account ============"
	echo -e "Configname	: http://$IP:85/$Login.ovpn"
	echo -e "Username	: $Login"
	echo -e "Password	: $Passwd"
	echo -e "Out of Date	: $exp"
	echo -e ""
	echo -e "สามารถใช้ได้ทั้งเครือข่าย Truemove และ Dtac"
	echo -e "หมายเหตุ : สำหรับ Truemove ใช้ได้เฉพาะซิมแบบเติมเงินเท่านั้น"
	echo -e "หมายเหตุ : สำหรับ Dtac ต้องสมัครโปรฯ Line ถึงจะสามารถใช้งาน VPN ได้"
	echo -e "============================="
	echo -e ""

elif test $x -eq 2; then
	echo ""
	read -p "Username : " User

	if getent passwd $User > /dev/null 2>&1; then
		userdel $User
		echo ""
		echo -e "ชื่อผู้ใช้ $User ได้ถูกลบออกจากระบบเรียบร้อยแล้ว"
		echo ""
	else
		echo ""
		echo -e "ไม่พบชื่อผู้ใช้ $User อยู่ในระบบ"
		echo ""
	fi
elif test $x -eq 3; then
	if [ -f /etc/debian_version ]; then
		UIDN=1000
	elif [ -f /etc/redhat-release ]; then
		UIDN=500
	else
		UIDN=500
	fi

	echo ""
	echo "-------------------------------------"
	while read checklist
	do
		account="$(echo $checklist | cut -d: -f1)"
		ID="$(echo $checklist | grep -v nobody | cut -d: -f3)"
		exp="$(chage -l $account | grep "Account expires" | awk -F": " '{print $2}')"
		if [[ $ID -ge $UIDN ]]; then
		printf "%-17s %2s\n" "$account" "$exp"
		fi
	done < /etc/passwd
	total="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
	echo "-------------------------------------"
	echo "รวมทั้งหมด : $total USER"
	echo "-------------------------------------"
	echo ""
elif test $x -eq 4; then
	if [ ! -e /usr/local/bin/reboot_otomatis ]; then
	echo '#!/bin/bash' > /usr/local/bin/reboot_otomatis 
	echo 'tanggal=$(date +"%m-%d-%Y")' >> /usr/local/bin/reboot_otomatis 
	echo 'waktu=$(date +"%T")' >> /usr/local/bin/reboot_otomatis 
	echo 'echo "เซิร์ฟเวอร์ได้รับการรีบูตเมื่อวันที่ $tanggal เวลา $waktu" >> /root/log-reboot.txt' >> /usr/local/bin/reboot_otomatis 
	echo '/sbin/shutdown -r now' >> /usr/local/bin/reboot_otomatis 
	chmod +x /usr/local/bin/reboot_otomatis
	fi

	echo "---------------------------------"
	echo "ตั้งค่าเวลารีบูทเซิฟเวอร์อัตโนมัติ"
	echo "---------------------------------"
	echo "1.  รีบูททุกๆ 1 ชั่วโมง"
	echo "2.  รีบูททุกๆ 6 ชั่วโมง"
	echo "3.  รีบูททุกๆ 12 ชั่วโมง"
	echo "4.  รีบูททุกๆ 1 วัน"
	echo "5.  รีบูททุกๆ 1 สัปดาห์"
	echo "6.  รีบูททุกๆ 1 เดือน"
	echo "7.  ปิดการรีบูทอัตโนมัติ"
	echo "8.  ดูบันทึกการรีบูทอัตโนมัติ"
	echo "9.  ลบบันทึกการรีบูทอัตโนมัติ"
	echo ""
	read -p "กรุณาเลือกหัวข้อที่ต้องการใช้งาน (ตัวเลข) : " x

	if test $x -eq 1; then
	echo "10 * * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 1 ชั่วโมงเรียบร้อยแล้ว"
	echo ""

	elif test $x -eq 2; then
	echo "10 */6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 6 ชั่วโมงเรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 3; then
	echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 12 ชั่วโมงเรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 4; then
	echo "10 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 1 วันเรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 5; then
	echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 1 สัปดาห์เรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 6; then
	echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
	echo ""
	echo "ตั้งค่ารีบูทอัตโนมัติทุกๆ 1 เดือนเรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 7; then
	rm -f /etc/cron.d/reboot_otomatis
	echo ""
	echo "ปิดการรีบูทอัตโนมัติเรียบร้อยแล้ว"
	echo ""
	elif test $x -eq 8; then
	if [ ! -e /root/log-reboot.txt ]; then
	echo ""
	echo "ไม่มีบันทึกในปัจจุบัน"
	echo ""
	else
	echo ""
	cat /root/log-reboot.txt
	echo ""
	fi
	elif test $x -eq 9; then
	echo "" > /root/log-reboot.txt
	echo ""
	echo "ทำการลบบันทึกเรียบร้อยแล้ว"
	echo ""
	else
	echo ""
	echo "ไม่มีตัวเลือกในเมนู กรุณาลองใหม่อีกครั้ง"
	echo ""
	exit
	fi
elif test $x -eq 5; then
        clear
        echo ""
        echo "รายชื่อผู้ใช้ที่กำลังใช้งานอยู่ในขณะนี้"
        echo "==========================================";

        if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
        fi
        if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure";
        fi
		
        data=( `ps aux | grep -i dropbear | awk '{print $2}'`);
        echo "รายชื่อผู้ใช้ที่ใช้งานพอร์ตของ Dropbear";
        echo "(ID - Username - IP)";
        echo "==========================================";
        cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt;
        for PID in "${data[@]}"
        do
        cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt;
        NUM=`cat /tmp/login-db-pid.txt | wc -l`;
        USER=`cat /tmp/login-db-pid.txt | awk '{print $10}'`;
        IP=`cat /tmp/login-db-pid.txt | awk '{print $12}'`;
        if [ $NUM -eq 1 ]; then
                echo "$PID - $USER - $IP";
		fi
        done
        echo " "
        echo "รายชื่อผู้ใช้ที่ใช้งานพอร์ตของ OpenSSH";
        echo "(ID - Username - IP)";
        echo "==========================================";
        cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.txt
        data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

        for PID in "${data[@]}"
        do
        cat /tmp/login-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
        NUM=`cat /tmp/login-db-pid.txt | wc -l`;
        USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
        IP=`cat /tmp/login-db-pid.txt | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
                echo "$PID - $USER - $IP";
        fi
        done
        if [ -f "/etc/openvpn/log.log" ]; then
	line=`cat /etc/openvpn/log.log | wc -l`
	a=$((3+((line-8)/2)))
	b=$(((line-8)/2))
	echo " "
	echo "รายชื่อผู้ใช้ที่ใช้งาน OpenVPN";
	echo "(Username - IP - วันนี้ - เวลาที่เชื่อมต่อ)";
	echo "==========================================";
	cat /etc/openvpn/log.log | head -n $a | tail -n $b | cut -d "," -f 1,2,5 | sed -e 's/,/   /g' > /tmp/vpn-login-db.txt
	cat /tmp/vpn-login-db.txt
        fi

        echo " "
        echo " "
        echo "==========================================";
        echo " "
elif test $x -eq 6; then
        echo ""
        read -p "Username Ban : " username
        egrep "^$username" /etc/passwd >/dev/null
        if [ $? -eq 0 ]; then
        passwd -l $username
        echo ""
        echo "ชื่อผู้ใช้ $username ได้ถูกแบนเรียบร้อยแล้ว"
	echo ""
        else
	echo ""
        echo "ไม่พบชื่อผู้ใช้ $username อยู่ในระบบ"
	echo ""
        exit 1
        fi
elif test $x -eq 7; then
        echo ""
	read -p "Username Unban : " username
        egrep "^$username" /etc/passwd >/dev/null
        if [ $? -eq 0 ]; then
        passwd -u $username
        echo ""
        echo "ชื่อผู้ใช้ $username ได้ถูกปลดแบนเรียบร้อยแล้ว"
	echo ""
        else
	echo ""
        echo "ไม่พบชื่อผู้ใช้ $username อยู่ในระบบ"
	echo ""
        exit 1
        fi
elif test $x -eq 8; then
        clear
        echo ""
        echo "ตรวจสอบดูตรงคำว่า Total ว่าได้ใช้ดาต้าไปทั้งหมดเท่าไหร่"
        echo "ในส่วนของแถว estimated คือการประมาณดาต้าที่ใช้ (ส่วนนี้ไม่ต้องสนใจ)"
        echo ""
        echo "หน่วยวัดขนาดของดาต้าจะแสดงเป็น MiB , GiB และ TiB"
        echo "MiB คือเมกะไบต์ (Megabyte หรือ Mb)"
        echo "GiB คิอกิกะไบต์ (Gigabyte หรือ Gb) (เช่น 1000Mb เท่ากับ 1Gb"
        echo "TiB คือเทราไบต์ (Terabyte หรือ Tb) (เช่น 1Tb เท่ากับ 1000Gb)"
	echo ""
        echo "หน่วยวัดที่แสดงเป็น rx (Receive) คือขนาดการรับข้อมูลจากทางผู้ใช้งานอินเตอร์เน็ตไปยังเซิฟเวอร์"
        echo "หน่วยวัดที่แสดงเป็น tx (Transmit) คือขนาดการส่งข้อมูลออกจากเซิฟเวอร์ให้กับผู้ใช้งานอินเตอร์เน็ต"
        echo "หน่วยวัดที่แสดงเป็น avg. rate (Average Rate) คืออัตราการใช้งานดาต้าต่อวินาที"
        echo ""
	sleep 3
	vnstat -m
elif test $x -eq 9; then
	speedtest --share
elif test $x -eq 10; then
	/etc/init.d/nginx restart
	service openvpn restart
	service cron restart
	service ssh restart
	service dropbear restart
	service squid3 restart
elif test $x -eq 11; then
	cd /usr/local/bin
	rm -f menu
	wget https://raw.githubusercontent.com/nwqionnwkn/OPENEXTRA/master/Config/menu
	chmod +x menu
	cd
elif test $x -eq 12; then
	exit
else
	clear
	menu
fi
