#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

username=trial
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Script by vps-murah.net"
  echo "Terimakasih sudah berlangganan di vps-murah.net"
  echo " "
  echo "Demikian Detail Account Trial Anda"
  echo "------------------------------"
  echo "   Host     : $MYIP" 
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo "   Port     : 22,80,109,143,443"
  echo "------------------------------"
  echo " "
  
else
  useradd trial
  usermod -s /bin/false trial
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Script by Kang wahid"
  echo "Terimakasih sudah berlangganan di Kang wahid"
  echo " "
  echo "Demikian Detail Account Trial Anda"
  echo "------------------------------"
  echo "   Host     : $MYIP"
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo "   Port     : 22,80,109,143,443"
  echo "------------------------------"
  echo " "
fi